language: python
python:
    - 3.4
    - 3.3
    - 2.7
sudo: false
addons:
  apt:
    packages:
    - texlive-base
    - pandoc
before_install:
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
install:
    # temporary while renaming propagates
    - pip install -f travis-wheels/wheelhouse . coveralls -r requirements.txt
    - pip install nbconvert[execute,serve,test]
    - python -m ipykernel.kernelspec --user
script:
    - nosetests -w /tmp --with-coverage --cover-package nbconvert nbconvert
after_success:
    - coveralls
