name: Generate Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: docker://pandoc/latex
        with:
          args: "--help" # gets appended to pandoc command
      - run: apk update && apk add texlive
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Cache pip on Linux
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python }}
      - run: latexmk -h
      - name: Install
        run: pip install -v ".[all]"
      - name: Build HTML docs
        run: python setup.py build_sphinx -b html
      - name: Build PDF docs
        run: |
          python setup.py build_sphinx -b latex
          cd docs
          make latexpdf
      - name: Check links
        run: python setup.py build_sphinx -b linkcheck

