name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install texlive-plain-generic inkscape texlive-xetex

          # pandoc is not up to date in the ubuntu repos, so we install directly
          wget https://github.com/jgm/pandoc/releases/download/2.14.2/pandoc-2.14.2-1-amd64.deb && sudo dpkg -i pandoc-2.14.2-1-amd64.deb

      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Cache pip on Linux
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}

      - name: Install package dependencies
        run: |
          pip install --upgrade setuptools pip pytest
          pip install -f travis-wheels/wheelhouse . codecov coverage
          pip install nbconvert[execute,serve,test]
          pip install check-manifest
          python -m ipykernel.kernelspec --user

      - name: List installed packages
        run: |
          pip freeze
          pip check

      - name: Run tests
        env:
          PYTHONWARNINGS: default
        run: |
          check-manifest --ignore "share/**"
          # cd so we test the install, not the repo
          cd `mktemp -d`
          py.test --cov nbconvert -v --pyargs nbconvert

      - name: Code coverage
        run: codecov
